steps:

#build docker container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hello-app', '.']
  
#push container to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/hello-app']
  
#deploy to cloud run
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - 'run'
#   - 'deploy'
#   - 'cloudrunservice'
#   - '--image'
#   - 'gcr.io/$PROJECT_ID/hello-app'
#   - '--region'
#   - 'us-central1'
#   - '--platform'
#   - 'managed'
#   - '--allow-unauthenticated'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cloudrunservice', '--image', 'gcr.io/pratik-333004/hello-app', '--region', 'us-central1']
images:
  - 'gcr.io/pratik-333004/hello-app'
